### ISSUE TITLE
Orion: history and extensions did not sync

### ISSUE THREAD

**Issue by benoitjadinon** [konabe-studio/konode#7]
konode 1.2.0, synced to github

`SyncEngine.syncType[history]
undefined is not an object (evaluating 'u.history.search')
Aug 7 at 09:30:12 PM
SyncEngine.syncType[extensions]
u.management.getAll is not a function. (In 'u.management.getAll()', 'u.management.getAll' is undefined)
Aug 7 at 09:30:12 PM`

bookmarks and sessions did sync.

thanks.

**Comment by benstone326** [comment]
Thank you for this. The two error strings were exactly what was needed, and the report ended up worth more than the bug it described: it sent me back through the rest of the code with the same question, and the same mistake was waiting in several other places.

**What was wrong.** Konode treated a permission its manifest asks for as proof that the browser implements the feature behind it. Those two errors are that assumption failing in two slightly different ways: `history` was not there at all, and `management` was there but carrying only some of its methods, so `getAll` was not a function. Konode called both anyway, every cycle, and reported the raw error with nothing to explain it. Bookmarks and sessions were unaffected, which is why the sync otherwise looked healthy.

Worth separating, because they need opposite handling and Konode was conflating them:

- the browser does not implement it, which nothing can fix, so it should be skipped quietly and marked unavailable
- the optional permission was never granted or was taken back later, which you can fix, so it should say which permission and how

**What changed in 1.2.1.** Konode now asks the browser what it can actually do, by checking whether the specific method is present rather than guessing from the engine, and it tells those two cases apart and says which one you are in. Whichever it is, the remaining data types keep syncing instead of the cycle failing over it.

I want to be straight about what this does and does not do: it does not add missing APIs to a browser. If Orion genuinely does not implement history and the extension list, those two types cannot sync there and Konode will now say so plainly in Settings instead of erroring. If the cause is a permission, Settings will name it and tell you where to grant it. **Which of the two it is on Orion is the thing I can't see from here**, and it is what the errors could not distinguish.

**If you have a few minutes to check.** 1.2.1 is live on [Firefox Add-ons](https://addons.mozilla.org/firefox/addon/konode/) now. Orion can run either build, so it depends which one you installed:

- the Firefox add-on: you either have 1.2.1 already or will shortly, since it updates itself
- the Chrome build: 1.2.1 is still in review on the Chrome Web Store, so either wait for it, or take `konode-chrome-1.2.1.zip` from the [v1.2.1 release](https://github.com/konabe-studio/konode/releases/tag/v1.2.1) and load it unpacked

What would help most is what Settings shows for History and Extensions after updating: whether each one reads as unavailable on this browser, or asks you for a permission. Either answer tells us something we don't currently know about Orion, and if it's the permission case, there's a good chance both types start working once it's granted.

I'll leave this open until you've had a chance to look.

**Comment by benoitjadinon** [comment]
thanks, works with the firefox 1.2.1 extension.

only small-ish issue is I specifically wrote the same device name as from the previous chromee extension backup, and I wished it asked me if I wanted to overwrite the existing one, cause we shouldn't care which extension was used to sync push, and which is used to sync pull, the data should be agnostic.
cause like, later on, if I reinstall Orion and use the Chrome extension, I will get stale data, you see ? also this creates duplicates.

<img width="1526" height="510" alt="Image" src="https://github.com/user-attachments/assets/1031d1ac-fac5-44bc-9822-5d1bbde20a78" />

the devices ui does not show which one is which, but we shouldn't care, the Mac Orion backup should be the Mac Orion backup.

<img width="1480" height="536" alt="Image" src="https://github.com/user-attachments/assets/0ffabdc8-f1d7-4802-8bfc-fe1281669bb7" />

I think 'devices' should be 'backups' and not specific to which extension we installed

thanks

**Comment by benstone326** [comment]
Great, thanks for confirming. Closing this one, since the sync failure it was about is fixed.

Thank you for the device naming point too. You are right about the intent, and we are building it: what should happen is that you type the name you already used and Konode picks up where that device left off, without you having to think about which extension pushed the data.

The reason it does not do that today, in one example. Say you keep both builds on the Mac and use them side by side, both called "Mac Orion". If Konode treated the same name as the same device, the two would write to the same file and each would read that file as its own, so they would never merge each other and whichever synced last would overwrite the other one's tabs and bookmarks. Your situation is the opposite and completely safe, because the old install is gone, but from inside the browser those two cases look identical: an extension cannot read the machine name, which is why Konode cannot tell them apart on its own. So instead of guessing it should ask you, and show you when each device last synced so the answer is obvious.

Written up with the full plan in #10, including your Brave comparison, which turned out to be a good argument for it: Brave's own device list has the same duplicate in it. Fair warning on timing, it is not going into the next release, which is a translations one, so this is the release after that.

Please do open another issue any time something like this comes up. Both of your reports have been unusually useful.
